name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.0.12
  - mlflow>=1.13.1
  - numpy=1.24.1
  - cookiecutter=1.7.2
  - hydra-core=1.0.6
  - matplotlib=3.6.2
  - pandas=1.2.3
  - git=2.30.2
  - markupsafe
  - pip=20.3.3
  - pip:
      - wandb==0.13.9
      - jinja2==2.10.1
      - gunicorn==20.1.0
      - databricks_cli


